export const meta = {
  slug: "pierscionek-zareczynowy-na-zamowienie",
  category: "jewelry",
  accent: "amber",
  publishedAt: "2026-04-17",
  updatedAt: "2026-04-17",
  coverImage: "/img/blog/pierscionek-zareczynowy.webp",
  readingTime: { pl: 7, en: 5, de: 5 },
  title: {
    pl: "Pierścionek zaręczynowy na zamówienie — koszt i proces",
    en: "Custom Engagement Ring — Cost, Process & Tips",
    de: "Verlobungsring nach Maß — Kosten, Prozess & Tipps",
  },
  description: {
    pl: "Ile kosztuje pierścionek zaręczynowy na zamówienie? Metal, kamienie, czas realizacji — kompletny przewodnik AEJaCA.",
    en: "How much does a custom engagement ring cost? From idea to finished ring — metals, gemstones, timeline. A complete guide by AEJaCA.",
    de: "Was kostet ein individueller Verlobungsring? Vom Entwurf bis zum fertigen Ring — Metalle, Edelsteine, Zeitrahmen. Ein vollständiger Leitfaden von AEJaCA.",
  },
  keywords: {
    pl: "pierścionek zaręczynowy na zamówienie, cena pierścionka zaręczynowego, custom engagement ring Polska, biżuteria na zamówienie Warszawa",
    en: "custom engagement ring cost, bespoke engagement ring process, handmade engagement ring Europe",
    de: "Verlobungsring nach Maß Kosten, individueller Verlobungsring Prozess, handgefertigter Verlobungsring Europa",
  },
  faq: {
    pl: [
      { q: "Ile kosztuje pierścionek zaręczynowy na zamówienie?", a: "Cena zależy od metalu, kamienia i stopnia skomplikowania. W AEJaCA zaczynamy od ok. 800 zł za prosty srebrny pierścionek. Złote pierścionki z kamieniami szlachetnymi to zwykle 3 000–15 000 zł. Wycenę otrzymasz w ciągu 24h po konsultacji." },
      { q: "Ile trwa realizacja pierścionka na zamówienie?", a: "Standardowy czas to 2–4 tygodnie od zatwierdzenia projektu. Dla projektów z odlewem metodą traconego wosku i osadzaniem kamieni — do 6 tygodni. Ekspresowa realizacja (7 dni) jest możliwa za dopłatą." },
      { q: "Czy mogę zobaczyć projekt przed produkcją?", a: "Tak — zawsze przygotowujemy render 3D (CAD) pierścionka z każdego kąta. Zatwierdzasz projekt wizualnie zanim rozpoczniemy produkcję. Zmiany na etapie CAD są bezpłatne." },
      { q: "Jakie metale i kamienie oferujecie?", a: "Pracujemy ze srebrem 925, złotem 585 (14K) i 750 (18K), oraz platyną. Kamienie: diamenty, moissanity, szafiry, szmaragdy, rubiny, ametysty i wiele innych naturalnych kamieni szlachetnych." },
    ],
    en: [
      { q: "How much does a custom engagement ring cost?", a: "It depends on the metal, stone, and complexity. At AEJaCA, simple silver rings start around €180. Gold rings with gemstones typically range €700–3,500. You'll receive a quote within 24h of your consultation." },
      { q: "How long does it take to make a custom ring?", a: "Standard timeline is 2–4 weeks from design approval. For lost-wax casting with stone setting, allow up to 6 weeks. Express production (7 days) is available for a surcharge." },
      { q: "Can I see the design before production?", a: "Yes — we always prepare a 3D CAD render from every angle. You approve the design visually before we begin production. Changes at the CAD stage are free." },
      { q: "What metals and stones do you offer?", a: "We work with 925 silver, 14K and 18K gold, and platinum. Stones include diamonds, moissanites, sapphires, emeralds, rubies, amethysts, and many other natural gemstones." },
    ],
    de: [
      { q: "Was kostet ein individueller Verlobungsring?", a: "Das hängt von Metall, Stein und Komplexität ab. Bei AEJaCA beginnen einfache Silberringe bei ca. 180 €. Goldringe mit Edelsteinen kosten typischerweise 700–3.500 €. Sie erhalten innerhalb von 24 Stunden ein Angebot." },
      { q: "Wie lange dauert die Anfertigung?", a: "Standardmäßig 2–4 Wochen ab Design-Freigabe. Für Wachsausschmelzguss mit Steinbesatz bis zu 6 Wochen. Express-Anfertigung (7 Tage) ist gegen Aufpreis möglich." },
      { q: "Kann ich das Design vor der Produktion sehen?", a: "Ja — wir erstellen immer einen 3D-CAD-Render aus jedem Winkel. Sie geben das Design visuell frei, bevor wir mit der Produktion beginnen. Änderungen im CAD-Stadium sind kostenlos." },
      { q: "Welche Metalle und Steine bieten Sie an?", a: "Wir arbeiten mit 925er Silber, 14K- und 18K-Gold sowie Platin. Edelsteine: Diamanten, Moissanite, Saphire, Smaragde, Rubine, Amethyste und viele andere." },
    ],
  },
  toc: {
    pl: [
      { id: "koszt", label: "Ile kosztuje" },
      { id: "proces", label: "Proces krok po kroku" },
      { id: "metal", label: "Wybór metalu" },
      { id: "kamien", label: "Kamień szlachetny" },
      { id: "czas", label: "Czas realizacji" },
      { id: "faq", label: "FAQ" },
    ],
    en: [
      { id: "cost", label: "How much it costs" },
      { id: "process", label: "Step-by-step process" },
      { id: "metal", label: "Choosing a metal" },
      { id: "stone", label: "Gemstone options" },
      { id: "timeline", label: "Timeline" },
      { id: "faq", label: "FAQ" },
    ],
    de: [
      { id: "kosten", label: "Kosten" },
      { id: "prozess", label: "Prozess Schritt für Schritt" },
      { id: "metall", label: "Metallauswahl" },
      { id: "stein", label: "Edelsteinoptionen" },
      { id: "zeitrahmen", label: "Zeitrahmen" },
      { id: "faq", label: "FAQ" },
    ],
  },
  relatedPosts: ["obraczki-slubne-na-zamowienie", "srebro-vs-zloto", "bizuteria-inwestycja"],
  relatedCalculators: [
    { to: "/jewelry/#calculator", icon: "💎", label: { pl: "Kalkulator biżuterii", en: "Jewelry Calculator", de: "Schmuckkalkulator" }, desc: { pl: "Wycena biżuterii na zamówienie", en: "Custom jewelry quote", de: "Schmuck nach Maß kalkulieren" } },
    { to: "/jewelry/#ring-blank", icon: "💍", label: { pl: "Kalkulator blanku obrączki", en: "Ring Blank Calculator", de: "Ring-Rohling-Rechner" }, desc: { pl: "Oblicz długość i masę blanku", en: "Calculate blank length and weight", de: "Rohlinglänge und -gewicht berechnen" } },
  ],
};
